### ISSUE TITLE
Accessing raw body is not possible

### ISSUE THREAD

**Issue by 24601** [nodeshift/faas-js-runtime#116]
There are several use cases where access to the raw body is important (e.g. calculating HMAC signatures when verifying webhooks, etc). 

Many APIs use such patterns to allow the webhook recipient to verify that the message is authentic and unmodified, but to calculate the HMAC of the body and compare it to the HMAC presented, one must have access to the *exact* body. Any difference at all will result in failure. 

We use the faas-js-runtime to handle Webhooks from a variety of APIs in our knative serving projects on OpenShift and need HMAC verification in the knative serving functions. 

To accomplish this, we have added the following line into the index.js file which allows us access to both the parsed body and the raw body. This introduces a "breaking" change, so we have not filed a PR for it, but will absolutely do so if this is desired or if a committer/project member can suggest a non-breaking pattern that matches desired convention of the project to accomplish this. 

We have considered changing the req object to include it, etc so as not to cause breaking API changes, so there are many ways, this was just most expedient for us, and we are, again, happy to hear how project norms/conventions may best accommodate this and submit a PR. 

```
  server.addContentTypeParser(
    'application/json',
    { parseAs: 'buffer' },
    function (req, body, done) {
      try {
        var newBody = {
          parsed: {...JSON.parse(body.toString())},
          raw: body
        }
        done(null, newBody)
      } catch (error) {
        error.statusCode = 400
        done(error, undefined)
      }
    }
  )
```

**Comment by 24601** [comment]
Using the decorator API, perhaps?

**Comment by lance** [comment]
@24601 thank you for this suggestion - apologies for the latency in responding here. It has been a whirlwind couple of weeks with Kubecon and travel. I wonder if simply proxying Fastify's [`request.raw` property](https://www.fastify.io/docs/latest/Reference/Request/) in the [`context` object](https://github.com/boson-project/faas-js-runtime/blob/64a1171df6ee248c239e67259f371284c75615a8/lib/context.js#L4-L11) would be sufficient. wdyt? Could you give that a try and see if it works for your scenario? If so, I think it's probably a better solution, as it doesn't break any existing interfaces and still keeps Fastify's nice and fast JSON parser.

**Comment by lance** [comment]
Ahh no - I played around with this approach and once Fastify has consumed the data from the stream, it's not there to access on the raw `IncomingRequest` object any longer. I will do something similar to what you have done here, but use Fastify's built-in JSON parser instead.

**Comment by jonirap** [comment]
This feature is desperately needed.
Any reason for it not to be implemented?

**Comment by lance** [comment]
Fixed in https://github.com/nodeshift/faas-js-runtime/pull/265
