### ISSUE TITLE
Killing the process hangs after a browser request

### ISSUE THREAD

**Issue by lance** [nodeshift/faas-js-runtime#120]
See https://gist.github.com/BethGriggs/2a6d0227b2747ecb72ff6d5eeb4d7977?permalink_comment_id=4221848#gistcomment-4221848

**Comment by helio-frota** [comment]
Solved in node 18.14.0
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.14.0
https://github.com/nodejs/node/issues/41578

:+1:

**Comment by helio-frota** [comment]
please don't close, I tested again and this is not 100% working...
