### ISSUE TITLE
Support for custom health and liveness checks

### ISSUE THREAD

**Issue by lejtmany** [nodeshift/faas-js-runtime#142]
Is there any way to customize the logic in the health and liveness check endpoints?

This would be useful for a function that is dependent on an external system (such as a database), we could incorporate some logic in the health endpoint to check that the connection is healthy.

Thank you!

**Comment by lholmquist** [comment]
I believe the only way to do that currently is with environment variables

**https://github.com/boson-project/faas-js-runtime/blob/14297d2f75a8df7604527459387b48a1eea3ee99/lib/health-check.js#L17-L18**

**Comment by lejtmany** [comment]
Right but that would just be to customize the path, is there a way to actually customize the code in the check?

**Comment by lance** [comment]
> Right but that would just be to customize the path, is there a way to actually customize the code in the check?

There is not. But I have been thinking lately that there needs to be some kind of lifecycle associated with loading a function so that function devs can do things like intercept these endpoints and/or add initialization code (think db connections, etc). I'd like to see something like this.

```js
// Initialization function called before the function is loaded as an endpoint
func init(server) {
  // ...
}

// override the /health/liveness endpoint
func liveness(request, reply) {
  // ...
}

// override the /health/readiness endpoint
func readiness(request, reply) {
  // ...
}

// intercept shutdown
func shutdown() {
  // ...
}

// The function handler
func handle(context, event) {
  // ...
}

module.exports = { init, liveness, readiness, shutdown, handle };
```

This is just back of the napkin brainstorming, but something we should be looking at.

**Comment by lance** [comment]
I have been doing a little work on this and have kind of been stalled trying to decide how to handle situations where only one of the checks is provided. It will require some refactoring, but it's coming...
