### ISSUE TITLE
User-container shutdown problem using the framework in a Knative Service

### ISSUE THREAD

**Issue by prushh** [nodeshift/faas-js-runtime#327]
### Description

Hi all,

I created a function project using the func CLI provided by Knative, specifically:
- `func create -l typescript -t cloudevents faas`

If I build and deploy the sample project using the CLI, everything works as expected.

I should install the Chromium package from the Alpine repository and use [Puppeteer](https://github.com/puppeteer/puppeteer) inside the project. I know more about the Docker container definition than Buildpacks; for this reason, I tried to define a Dockerfile to deploy the sample function (where I only downgrade @types/node to v18.18.2 without any additions) as a Knative Service, using `kubectl apply`.

```Dockerfile
# syntax=docker/dockerfile:1
FROM node:18.18.2-alpine

WORKDIR /workdir

COPY . .
RUN npm install && \
    npm run build

CMD npm start
```

Still, during the shutdown of the Pod, only the queue-proxy container is stopped correctly. The user container stops receiving readiness/liveness requests but remains in the _Ready_ state even though it has received the shutdown signal. Only after some time is it killed. Two screenshots are attached for details.

Could it be a framework issue or more func/serving problem?

### Configurations

- minikube v1.31.2
- k8s v1.27.4
- func v0.38.0-99-gcd0bc6ae (installed using brew)
- knative-serving v1.12.0 (installed using YAML files)

### k9s overview
<img width="1792" alt="pod-details" src="https://github.com/nodeshift/faas-js-runtime/assets/33416316/4148de1a-2487-49a1-8409-301388bdfea6">

### kubectl describe pod
<img width="1680" alt="pod-describe" src="https://github.com/nodeshift/faas-js-runtime/assets/33416316/380f923a-4765-4065-9454-3472c9afd0a8">

**Comment by lholmquist** [comment]
My initial thought is that it is something more high level than the framework.  The faas-js-rutime is basically just running a fastify server to run the functions.  is there a way to see if there is a node.js process still running?

**Comment by richardlau** [comment]
It's probably because `npm start` is being used -- this may not pass on any signals to the running application. 
References:
- https://developers.redhat.com/articles/2021/08/26/introduction-nodejs-reference-architecture-part-5-building-good-containers?source=sso#avoid_common_pitfalls_when_running_a_process_in_a_container
- https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#cmd

**Comment by prushh** [comment]
I change the Dockerfile as follow:

```Dockerfile
# syntax=docker/dockerfile:1
FROM node:18.18.2-alpine

WORKDIR /workdir

ARG FUNC_LOG_LEVEL=info

COPY . .
RUN npm install && \
    npm run build

CMD ["./node_modules/faas-js-runtime/bin/cli.js", "./build/index.js"]
```

Now the shutdown works well but not the logging. I tried also
`CMD ["FUNC_LOG_LEVEL=info", "./node_modules/faas-js-runtime/bin/cli.js", "./build/index.js"]`
without the ARG but doesn't work.

Some suggestions?
