### ISSUE TITLE
Change charset parameter of default content-type header values from "utf8" to "utf-8"

### ISSUE THREAD

**Issue by flaheathrenn** [nodeshift/faas-js-runtime#329]
Per [IANA](https://www.iana.org/assignments/character-sets/character-sets.xhtml), the preferred MIME name for the UTF-8 charset is `utf-8`, not `utf8`.

**Comment by lholmquist** [comment]
closing, PR merged!

**Comment by lholmquist** [comment]
This is now released on npm as 2.3.0
