### ISSUE TITLE
Add support for CORS

### ISSUE THREAD

**Issue by giurgiur99** [nodeshift/faas-js-runtime#347]
At the moment, faas-js-runtime is configured to use "*" as cors settings and preflight (OPTIONS) is not configured, thus resulting in CORS errors. 

**lib/invoker.js**
```javascript
 return async function invokeFunction(context, log) {
    // Default payload values
    const payload = {
      code: 200,
      response: undefined,
      headers: {
        'content-type': 'application/json; charset=utf8',
        'access-control-allow-methods':
          'OPTIONS, GET, DELETE, POST, PUT, HEAD, PATCH',
        'access-control-allow-origin': '*'
      }
    };
```

My proposal is to use the actual settings as default but enable the user to export corsSettings in the Function interface
**index.d.ts**
```typescript
export interface Function {
  // The initialization function, called before the server is started
  // This function is optional and should be synchronous.
  init?: () => any;

  // The shutdown function, called after the server is stopped
  // This function is optional and should be synchronous.
  shutdown?: () => any;

  corsSettings? :() => any;
}
```

**Comment by lholmquist** [comment]
That sounds like a reasonable addition.   Is this something you were thinking of contributing? 

Also,  could you post the error you are getting?

**Comment by giurgiur99** [comment]
I have prepared something, how can i contribute to this repo?

**Comment by giurgiur99** [comment]
Here is the PR:
https://github.com/nodeshift/faas-js-runtime/pull/359

**Comment by lholmquist** [comment]
This is in the newest release 2.4.0
