### ISSUE TITLE
Cannot set content-type : application/pdf into response of function

### ISSUE THREAD

**Issue by BNT0206** [nodeshift/faas-js-runtime#361]
I tried to create a function that returns a pdf, but I couldn't set the response to content-type: application/pdf. I make some changes in function (localy)that returns exactly what I wanted.

**Comment by lholmquist** [comment]
if you were able to make it work, would you want to send a PR?

**Comment by BNT0206** [comment]
i open issue with my student account, i send a PR with other account, any problem with that?

**Comment by lholmquist** [comment]
sounds good

**Comment by BNT0206** [comment]
Sorry for create an this issue, the template that i get was created with 2.2.2. I forgot to see the version, i see a lot of things and forgot to see this.
